kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /proc
      containerPath: /procHost
- role: worker
  extraMounts:
    - hostPath: /proc
      containerPath: /procHost
- role: worker
  extraMounts:
    - hostPath: /proc
      containerPath: /procHost
- role: worker
networking:
  disableDefaultCNI: true


# https://tetragon.io/docs/getting-started/install-k8s/
# https://raw.githubusercontent.com/cilium/cilium/1.13.1/Documentation/installation/kind-config.yaml