name: cilium-kind

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read


jobs:
  specs:
    name: cilium-kind
    runs-on: [actuated-arm64-4cpu-8gb]
    #, actuated-dev]
    # runs-on: actuated-4cpu-8gb
    steps:

      - name: Look for btf in sys
        run: find /sys/kernel/btf
      - uses: actions/checkout@v1

      - uses: alexellis/arkade-get@master
        with:
          kind: latest
          kubectl: latest
          stern: latest
          cilium: latest
      - name: Setup Kind
        run: |
          sudo chmod +x $HOME/.arkade/bin/*
          sudo cp -r $HOME/.arkade/bin/* /usr/local/bin/

          # curl -LO https://raw.githubusercontent.com/cilium/cilium/1.13.1/Documentation/installation/kind-config.yaml
          kind create cluster --config=./kind-config.yaml
      - name: Setup Cilium
        run: |
          cilium install

      # - name: Attach SSH
      #   uses: self-actuated/connect-ssh@master

      - name: Cilium full check
        run: |
         cilium status --wait

      - name: Cilium logs check
        run: |
          kubectl get pods -n kube-system
          kubectl logs  -n kube-system -l "app.kubernetes.io/name=cilium-agent" || :

      # - name: Install tetragon
      #   run: |
      #     EXTRA_HELM_FLAGS="--set teragon.hostProcPath=/procHost" # flags for helm install
      #     helm repo add cilium https://helm.cilium.io
      #     helm repo update
      #     helm install tetragon ${EXTRA_HELM_FLAGS} cilium/tetragon -n kube-system
      #     kubectl rollout status -n kube-system ds/tetragon

      # - name: Run sample app by Tetragon
      #   run: |
      #     kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.15.0-pre.1/examples/minikube/http-sw-app.yaml
      #     kubectl get pods


